variable "db_subnet_ids" {}
variable "nodes" {}
variable "engine" {}
variable "availability_zones" {}
variable "instance_class" {}
variable "pub_access" {}
variable "apply_immediately" {}
variable "engine_version" {}
variable "db_name" {}
variable "master_user" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "iam_database_authentication_enabled" {}
variable "enabled_cloudwatch_logs_exports" {}
variable "skip_final_snapshot" {}
variable "sg_rds" {}
variable "monitoring_interval" {}
variable "performance_insights_enabled" {}
variable "performance_insights_retention_period" {}